version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: CU_TR_CU_MYSQL
    restart: always
    env_file:
      - src/config/.env
      - src/config/.share.env
    environment:
      - MYSQL_HOST=${MYSQL_HOSTNAME}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'