export class Constains {
  public static ADMIN_REPOSITORY = "ADMIN_REPOSITORY";
  public static POST_CONTENT_REPOSITORY = "POST_CONTENT_REPOSITORY";
  public static POST_IMAGE_REPOSITORY = "POST_IMAGE_REPOSITORY";
  public static POST_CATEGORY_REPOSITORY = "POST_CATEGORY_REPOSITORY";  
  public static PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
  public static PROJECT_REPOSITORY = 'PROJECT_REPOSITORY';
  public static DATA_SOURCE = 'DATA_SOURCE';
}
